- hosts: localhost
  connection: local
 
  vars:
    homebrew_taps:
      - homebrew/dupes
      - homebrew/versions
      - homebrew/boneyard
    homebrew_packages:
      - name: awscli
      - name: ansible
      - name: direnv
      - name: fzf
      - name: git
      - name: python
      - name: python3
      - name: terraform
      - name: the_silver_searcher
      - name: tig
      - name: tmux
      - name: zsh
      - name: zsh-completions
      - name: zsh-syntax-highlighting
      - name: vim
      - name: go
      - name: wget
      - name: mas
 
  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes
    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'
    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'
 
